---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certissuers.certmaster.kuberails.com
spec:
  additionalPrinterColumns: []
  group: certmaster.kuberails.com
  names:
    kind: CertIssuer
    plural: certissuers
    shortNames: []
    singular: certissuer
  scope: Namespaced
  subresources: {}
  versions:
    - name: v1
      served: true
      storage: true
