---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: certissuers.certmaster.kuberails.com
spec:
  group: certmaster.kuberails.com
  names:
    kind: CertIssuer
    plural: certissuers
    shortNames: []
    singular: certissuer
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        "openAPIV3Schema":
          type: object
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: "Issuer"
              required: ["domainName", "dnsProvider"]
              type: object
              properties:
                domainName:
                  type: string
                dnsProvider:
                  type: object
                  required: ["provider"]
                  properties:
                    provider: { "type": "string" }
                    key: { "type": "string" }
                    secretKey: { "type": "string" }
                    accessKey: { "type": "string" }
                    secretAccessKey: { "type": "string" }
                    region: { "type": "string" }
                    hostedZoneId: { "type": "string" }
                  oneOf:
                    - properties:
                        provider:
                          enum: ["digitalocean"]
                      required: ["provider", "key", "secretKey"]
                    - properties:
                        provider:
                          enum: ["cloudflare"]
                      required: ["provider", "key", "secretKey"]
                    - properties:
                        provider:
                          enum: ["route53"]
                      required: ["accessKey", "secretAccessKey", "region"]
                secretName:
                  type: string
                  nullable: true
                namespaces:
                  type: array
                  nullable: true
                  items:
                    type: string
