apiVersion: certmaster.kuberails.com/v1
kind: CertIssuer
metadata:
  name: com-digitalocean-kuberails
spec:
  domainName: kuberails.com
  namespaces:
    - default
    - kuberails
    - avencera
    - doesnt-exist
  dnsProvider:
    provider: digitalocean
    authToken: "DO_TOKEN_GOES_HERE"
