apiVersion: certmaster.kuberails.com/v1
kind: CertIssuer
metadata:
  name: com-error-kuberails
  namespace: praveen
spec:
  domainName: kuberails.com
  namespaces:
    - default
    - kuberails
  dnsProvider:
    provider: CloudFlare
    key: thisIsMyKey
    secretKey: thisIsMySecretKey
