apiVersion: certmaster.kuberails.com/v1
kind: CertIssuer
metadata:
  name: com-ok-kuberails
spec:
  domainName: praveenperera.com
  namespaces:
    - default
    - praveen
    - avencera
    - doesnt-exist
  dnsProvider:
    provider: cloudflare
    key: thisIsMyKey
    secretKey: thisIsMySecretKey
