apiVersion: certmaster.kuberails.com/v1
kind: CertIssuer
metadata:
  name: com-ok-kuberails
  namespace: kuberails
spec:
  domainName: praveenperera.com
  dnsProvider:
    provider: cloudflare
    key: thisIsMyKey
    secretKey: thisIsMySecretKey
